import { AuthUser } from "./user";

export interface Penalty {
  id: number;
  amount: number;
  reason: string;
  reasonType: string;
  status: string;
  penaltyDate: string;
  autoGenerated: boolean;
  adminComment: string | null;
  user: AuthUser & {
    phone?: string;
  };
}