"use client";

import { useEffect, useState } from "react";
import Modal from "@/components/common/Modal";
import TextInput from "@/components/common/TextInput";
import PrimaryButton from "@/components/common/PrimaryButton";
import { api } from "@/lib/api";
import { Penalty } from "@/types/penalty";

interface PenaltyFormModalProps {
  open: boolean;
  onClose: () => void;
  onSuccess: () => void;
  editData?: Penalty | null;
}

const initialForm = {
  userId: "",
  amount: "",
  reason: "",
  reasonType: "manual",
  status: "pending",
  penaltyDate: "",
  autoGenerated: "false",
  adminComment: "",
};

export default function PenaltyFormModal({
  open,
  onClose,
  onSuccess,
  editData,
}: PenaltyFormModalProps) {
  const [form, setForm] = useState(initialForm);
  const [loading, setLoading] = useState(false);
  const [errorText, setErrorText] = useState("");

  useEffect(() => {
    if (editData) {
      setForm({
        userId: String(editData.user?.id ?? ""),
        amount: String(editData.amount ?? 0),
        reason: editData.reason || "",
        reasonType: editData.reasonType || "manual",
        status: editData.status || "pending",
        penaltyDate: editData.penaltyDate || "",
        autoGenerated: String(editData.autoGenerated ?? false),
        adminComment: editData.adminComment || "",
      });
    } else {
      setForm(initialForm);
    }
  }, [editData, open]);

  const setValue = (key: string, value: string) => {
    setForm((prev) => ({ ...prev, [key]: value }));
  };

  const handleSubmit = async () => {
    try {
      setLoading(true);
      setErrorText("");

      const payload = {
        userId: Number(form.userId),
        amount: Number(form.amount || 0),
        reason: form.reason,
        reasonType: form.reasonType,
        status: form.status,
        penaltyDate: form.penaltyDate,
        autoGenerated: form.autoGenerated === "true",
        adminComment: form.adminComment || null,
      };

      if (editData) {
        await api.put(`/penalties/${editData.id}`, payload);
      } else {
        await api.post("/penalties", payload);
      }

      onSuccess();
      onClose();
    } catch (error: any) {
      setErrorText(
        error?.response?.data?.message || "So‘z narxini saqlashda xatolik yuz berdi"
      );
    } finally {
      setLoading(false);
    }
  };

  return (
    <Modal
      open={open}
      onClose={onClose}
      title={editData ? "So‘z narxini tahrirlash" : "So‘z narxi qo‘shish"}
    >
      <div className="space-y-5">
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
          <TextInput
            label="User ID"
            type="number"
            value={form.userId}
            onChange={(e) => setValue("userId", e.target.value)}
          />

          <TextInput
            label="Summa"
            type="number"
            value={form.amount}
            onChange={(e) => setValue("amount", e.target.value)}
          />

          <TextInput
            label="Sabab"
            value={form.reason}
            onChange={(e) => setValue("reason", e.target.value)}
          />

          <TextInput
            label="Sana"
            type="date"
            value={form.penaltyDate}
            onChange={(e) => setValue("penaltyDate", e.target.value)}
          />

          <div className="space-y-2">
            <label className="text-sm font-medium text-slate-700">Turi</label>
            <select
              value={form.reasonType}
              onChange={(e) => setValue("reasonType", e.target.value)}
              className="w-full rounded-xl border border-slate-300 px-4 py-3 outline-none"
            >
              <option value="manual">manual</option>
              <option value="late">late</option>
              <option value="plan_warning">plan_warning</option>
            </select>
          </div>
          <div className="space-y-2">
            <label className="text-sm font-medium text-slate-700">Status</label>
            <select
              value={form.status}
              onChange={(e) => setValue("status", e.target.value)}
              className="w-full rounded-xl border border-slate-300 px-4 py-3 outline-none"
            >
              <option value="pending">pending</option>
              <option value="done">done</option>
              <option value="not_done">not_done</option>
            </select>
          </div>
        </div>

        <div className="space-y-2">
          <label className="text-sm font-medium text-slate-700">Admin izoh</label>
          <textarea
            value={form.adminComment}
            onChange={(e) => setValue("adminComment", e.target.value)}
            className="min-h-[120px] w-full rounded-xl border border-slate-300 px-4 py-3 outline-none"
          />
        </div>

        {errorText ? (
          <div className="rounded-xl bg-red-50 px-4 py-3 text-sm text-red-600">
            {errorText}
          </div>
        ) : null}

        <div className="flex justify-end gap-3">
          <button
            onClick={onClose}
            className="rounded-xl border border-slate-300 px-5 py-3 text-slate-700"
          >
            Bekor qilish
          </button>
          <PrimaryButton onClick={handleSubmit} disabled={loading}>
            {loading ? "Saqlanmoqda..." : "Saqlash"}
          </PrimaryButton>
        </div>
      </div>
    </Modal>
  );
}